# aws cloudformation package ... should work for this
AWSTemplateFormatVersion: "2010-09-09"
Description: "Cloudformation template for all the resources"

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "uuid"
          AttributeType: "S"  
      KeySchema:
        - AttributeName: "uuid"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "2"
        WriteCapacityUnits: "2"

  CreateTodo:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Code: 
        S3Bucket: todo
        S3Key: code/create-todo.zip
      Runtime: "nodejs12.x"
      Role: !GetAtt LambdaExecutionRole.Arn


  # ReadTodo:
  #   Type: AWS::Lambda::Function
  #   Properties:
  #     Code: 
  #       - ZipFile: "./zips/read-todo.zip"
  #     Runtime: "nodejs12.x"
  #     Role: !GetAtt LambdaExecutionRole